# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20170220_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedemail',
            name='audience',
            field=models.CharField(choices=[('with_team', 'Participants with a team'), ('no_team', 'Participants without a team'), ('all', 'Blue Team Participants (All)'), ('red_team_all', 'Red Team Members (All)'), ('red_team_approved', 'Red Team Members (Approved)'), ('green_team_all', 'Green Team Members (All)'), ('green_team_approved', 'Green Team Members (Approved)'), ('everyone', 'Everyone')], max_length=30),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='looking_for_team',
            field=models.BooleanField(default=False, help_text='ISEAGE will put you on a team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='looking_for_members',
            field=models.BooleanField(default=True, help_text='Allow anyone to join your team; uncheck if your team is full.'),
        ),
    ]
