# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20180520_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='green_docs_url',
            field=models.URLField(help_text=b'Where green team members can go to see their documentation. Usually a Google Drive folder.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='red_docs_url',
            field=models.URLField(help_text=b'Where red team members can go to see their documentation. Usually a Google Drive folder.', null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name=b'documentation_url',
            field=models.CharField(blank=True, help_text=b'Where blue teams can go to see their documentation. Usually a Google Drive folder.', max_length=200, null=True),
        ),
    ]
